#!/usr/bin/env python
# -*- coding: utf-8 -*- #
import os

# Need absolute path so that running with fab works
project_path = os.path.dirname(os.path.realpath(__file__))

AUTHOR = u'Nick Roth'

SITENAME = u'nickroth'
SITESUBTITLE = u'Systems engineering, data analytics, programming'
SITEURL = '' #change in publishconf.py
RELATIVE_URLS = True
DISQUS_SITENAME = 'nickroth'
GOOGLE_ANALYTICS = 'UA-49251486-1'

PATH = 'content'

# Times and dates
DEFAULT_DATE_FORMAT = '%b %d, %Y'
TIMEZONE = 'US/Central'
DEFAULT_LANG = u'en'

# Set the article URL
ARTICLE_URL = 'blog/{date:%Y}/{date:%m}/{date:%d}/{slug}/'
ARTICLE_SAVE_AS = 'blog/{date:%Y}/{date:%m}/{date:%d}/{slug}/index.html'

# Title menu options
MENUITEMS = [('LinkedIn', 'https://www.linkedin.com/in/nicholasleeroth')]
NEWEST_FIRST_ARCHIVES = False

#Github include settings
GITHUB_USER = 'rothnic'
#GITHUB_REPO_COUNT = 0
#GITHUB_SKIP_FORK = True
GITHUB_SHOW_USER_LINK = True

# Blogroll
#LINKS =  (('Pelican', 'http://docs.notmyidea.org/alexis/pelican/'),
#          ('Python.org', 'http://python.org'),
#          ('Jinja2', 'http://jinja.pocoo.org'),
#          ('You can modify those links in your config file', '#'),)

# Social widget
#SOCIAL = (('You can add links in your config file', '#'),
#          ('Another social link', '#'),)

DEFAULT_PAGINATION = 10

# This requires Pelican 3.3+
# Copies files on build. CNAME supports custom hostname with gh-pages
CNAME = os.path.join('extra', 'CNAME')
STATIC_PATHS = ['images', 'figures', 'downloads', 'favicon.png', CNAME]
EXTRA_PATH_METADATA = {CNAME: {'path': 'CNAME'}}

CODE_DIR = 'downloads/code'
NOTEBOOK_DIR = 'downloads/notebooks'

# Theme and plugins
THEME = 'theme/pelican-bootstrap3'
PLUGIN_PATHS = ['./pelican-plugins']
PLUGINS = ['liquid_tags.img', 'liquid_tags.video',
           'liquid_tags.youtube', 'liquid_tags.vimeo',
           'liquid_tags.include_code', 'liquid_tags.notebook',
           'summary']
DISPLAY_PAGES_ON_MENU = False

"""
The theme file should be updated so that the base header contains the line:
  {% if EXTRA_HEADER %}
    {{ EXTRA_HEADER }}
  {% endif %}

This header file is automatically generated by the notebook plugin
"""
NB_HEADER = os.path.join(project_path, '_nb_header.html')
if not os.path.exists(NB_HEADER):
    import warnings
    warnings.warn("_nb_header.html not found.  "
                  "Rerun make html to finalize build.")
else:
    EXTRA_HEADER = open(NB_HEADER).read().decode('utf-8').replace(
        "highlight ", "highlight-ipynb ")


"""
The following block handles the livereload functionality for instant reloads when the project is rebuilt on each change to the content files.

You need to add the following to your base template header:

{% if LIVE_RELOAD %}
    <script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')</script>
{% endif %}

You will need to run the livereload server as well. I used the livereload plugin for the Atom editor, but others should work fine as well, as long as the default port is used.
"""
LIVE_RELOAD = True

# Sharing
TWITTER_USER = 'rothnic'
GOOGLE_PLUS_USER = 'NickRoth86'
GOOGLE_PLUS_ONE = True
GOOGLE_PLUS_HIDDEN = False
FACEBOOK_LIKE = False
TWITTER_TWEET_BUTTON = True
TWITTER_LATEST_TWEETS = True
TWITTER_FOLLOW_BUTTON = True
TWITTER_TWEET_COUNT = 3
TWITTER_SHOW_REPLIES = 'false'
TWITTER_SHOW_FOLLOWER_COUNT = 'false'


# RSS/Atom feeds
FEED_DOMAIN = SITEURL
FEED_ATOM = 'atom.xml'


# Search
SEARCH_BOX = True

# Bootstrap
BOOTSTRAP_THEME = 'paper'
BOOTSTRAP_NAVBAR_INVERSE = True
